name: Deploy Lambda

on:
  push:
    tags:
    - "*"

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: yvesgurcan/deploy-lambda-function@v0.0.5
        with:
          package: ${{github.workspace}}/${{ github.event.repository.name }}.zip
          function-name: MMedia-Lex-Lambda
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_LAMBDA_ACCESS_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_LAMBDA_SECRET_KEY }}
